#!/bin/sh

wmctrl -r urxvt -e 0,0,14,1366,742

FIFO="/tmp/dvtm-status.$$"
[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
	# echo "${acpi -b | ag -o "[0-9]{1,3}\%"} ${date +%H:%M}"
#	echo "Battery: $(acpi -b | ag -o "[0-9]{1,3}\%") | $(uptime -p)                               "
#	echo "$(fortune -n 130 -s | tr '\n' ' ' | tr '[:blank:]' ' ' | sed -e 's/ --.*$//') | Battery: $(acpi -b | ag -o "[0-9]{1,3}\%") | $(uptime -p)  "
	echo "$(fortune -n 130 -s | tr '\n' ' ' | sed -r -e 's/[ \t]/ /g') | Battery: $(acpi -b | ag -o "[0-9]{1,3}\%") | $(uptime -p)  "
        sleep 60
done > "$FIFO" &

STATUS_PID=$!
dvtm -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
