#!/bin/mksh

BG="#000000"
FG="#ffffff"
CACHE_PATH=$HOME/.config/dwm/dmenu_list
# CACHE_PATH=/tmp/dmenu_list

dmenu -i -b -p EXEC -nb "$BG" -nf "$FG" -sb "$FG" -sf "$BG" -fn "tewi" <  $CACHE_PATH | mksh &
exit 0
